// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentStatus = "starting" | "idle" | "working" | "needs_input" | "finished" | "error";
