// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSettings } from "./AgentSettings";
import type { GlobalSettings } from "./GlobalSettings";

export type AppSettings = { global: GlobalSettings, agents: { [key in string]?: AgentSettings }, };
