// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrustLevel } from "./TrustLevel";

export type ArbiterStateRow = { project_id: string, trust_level: TrustLevel, loop_status: string, current_story_id: string | null, iteration_count: number, max_iterations: number, last_activity_at: string | null, };
