// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Consolidation = { id: string, project_id: string, source_ids_json: string, summary: string, insight: string, created_at: string, };
