// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContextUnit = { id: string, project_id: string | null, name: string, type: string, scope: string, tags_json: string, l0_summary: string | null, l1_overview: string | null, l2_content: string | null, created_at: string, updated_at: string, };
