// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GlobalSettings = { theme: string, font_family: string, font_size: number, notifications_enabled: boolean, minimize_to_tray: boolean, terminal_scrollback: number, arbiter_timeout_seconds: number, arbiter_provider: string, arbiter_model: string, };
