// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Memory = { id: string, project_id: string, session_id: string | null, visibility: string, content: string, summary: string | null, entities_json: string, topics_json: string, importance: number, consolidated: boolean, created_at: string, };
