// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Project = { id: string, name: string, path: string, created_at: string, git_enabled: boolean, arbiter_enabled: boolean, arbiter_agent_type: string | null, };
