// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QualityGateConfig = { build_command: string | null, lint_command: string | null, typecheck_command: string | null, test_command: string | null, arbiter_judge: boolean, };
