// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Story = { id: string, project_id: string, title: string, description: string, acceptance_criteria: string | null, priority: number, status: string, depends_on_json: string, iteration_attempts: number, created_at: string, };
