use super::personas::BundledUnit;

pub static BUNDLED_MCP_UNITS: &[BundledUnit] = &[
    BundledUnit {
        slug: "mcp-reverse-proxy",
        name: "Reverse Proxy MCP",
        unit_type: "mcp",
        l0_summary: "Agent control channel — status reporting, guidance requests, and completion signaling via MCP tools.",
        l1_overview: "## Reverse Proxy MCP\n\n**Purpose:** Provides structured communication between AI agents and ove.run, replacing terminal output parsing with typed MCP tool calls.\n\n**Tools:**\n- `check_in` — Report status and get project context at task start\n- `request_guidance` — Ask the user a question and wait for a response\n- `report_completion` — Signal task completion and get quality gate results\n\n**Environment Variables:**\n- `OVE_SESSION_ID` — Your PTY session identifier\n- `OVE_PROJECT_PATH` — Absolute path to the project root\n\n**When to use:** Call `check_in` at the start of every task. Call `request_guidance` when blocked. Call `report_completion` when done.",
        l2_content: "# Reverse Proxy MCP — Agent Control Tools\n\nThese tools allow you to communicate structured status and requests to ove.run instead of relying on terminal output patterns.\n\n## check_in\n\n**Call this before starting work on any task.** It returns relevant project context, memories, and pending instructions.\n\n**Parameters:**\n- `project_path` (required) — Read from `OVE_PROJECT_PATH` env var\n- `session_id` (required) — Read from `OVE_SESSION_ID` env var\n- `task_summary` (required) — Brief description of what you're about to do\n- `status` (required) — One of: `starting`, `working`, `blocked`\n\n**Returns:** `memories`, `context` (L0 summaries), `pending_instructions`, `acknowledged`\n\n## request_guidance\n\n**Call when you need a decision from the user** or encounter an ambiguity. This will pause execution and wait for the user's response (up to 5 minutes).\n\n**Parameters:**\n- `project_path` (required)\n- `session_id` (required)\n- `question` (required) — What you need decided or clarified\n- `options` (optional) — Array of possible choices\n- `allow_free_input` (optional, default true) — Whether free text is allowed\n\n**Returns:** `response` (the answer), `option_index` (if applicable), `auto_resolved` (if arbiter answered)\n\n## report_completion\n\n**Call when you have completed the assigned task.** This triggers quality gate checks (build, lint, test) and returns results so you can fix issues before finishing.\n\n**Parameters:**\n- `project_path` (required)\n- `session_id` (required)\n- `summary` (required) — What was accomplished\n- `files_changed` (optional) — List of files modified\n- `confidence` (optional) — `high`, `medium`, or `low`\n\n**Returns:** `gate_results` (array of name/passed/output), `acknowledged`\n\n**Self-correction flow:** If gates fail, fix the issues and call `report_completion` again. The agent handles its own corrections within a single session.",
    },
    BundledUnit {
        slug: "mcp-memory-proxy",
        name: "Memory Proxy MCP",
        unit_type: "mcp",
        l0_summary: "Project context and memory access — search context units, memories, and notes via MCP tools.",
        l1_overview: "## Memory Proxy MCP\n\n**Purpose:** Provides read access to the project's context store, memory system, and notes through MCP tools.\n\n**Tools:**\n- `list_context` — Discover all context units with L0 summaries\n- `get_context` — Get full L1/L2 content for a specific unit\n- `search_context` — Full-text search across context\n- `list_memories` — List project memories by importance\n- `search_memories` — Full-text search across memories\n- `list_notes` — List notes marked for agent inclusion\n\n**When to use:** Call `list_context` to discover available knowledge. Use `search_memories` when you need project-specific learnings. Use `list_notes` for user-flagged information.",
        l2_content: "# Memory Proxy MCP — Context & Memory Tools\n\nThese tools provide read access to ove.run's project knowledge base.\n\n## list_context\n\nList all context units (personas, skills, knowledge, references) for the project with their one-sentence L0 summaries. Use this to discover available context before requesting full content.\n\n**Parameters:** `project_path` (required)\n**Returns:** Array of `{ id, name, type, l0_summary }`\n\n## get_context\n\nGet the full L1 overview and L2 content for a specific context unit by ID.\n\n**Parameters:** `project_path` (required), `id` (required — from list_context)\n**Returns:** `{ id, name, type, l1_overview, l2_content }`\n\n## search_context\n\nFull-text search across context unit names, summaries, and content.\n\n**Parameters:** `project_path` (required), `query` (required — search terms)\n**Returns:** Array of matching `{ id, name, type, l0_summary }`\n\n## list_memories\n\nList project-level memories ordered by importance. Memories are automatically extracted facts and patterns from past agent sessions.\n\n**Parameters:** `project_path` (required)\n**Returns:** Array of `{ id, content, summary, importance, topics }`\n\n## search_memories\n\nFull-text search across project memories. Returns top 10 by relevance.\n\n**Parameters:** `project_path` (required), `query` (required)\n**Returns:** Array of matching memories\n\n## list_notes\n\nList notes that have been marked for agent context inclusion by the user.\n\n**Parameters:** `project_path` (required)\n**Returns:** Array of `{ id, title, content }`",
    },
];
